name: Build Qt WebKit

on:
  push:
    branches:
      - qtwebkit-5.14.1
  pull_request:
    branches:
      - qtwebkit-5.14.1

jobs:
  build:
    runs-on: centos7-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker
        uses: docker/setup-docker-action@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Qt WebKit
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential perl python gawk libssl-dev bison flex
          cd qtwebkit
          perl Tools/Scripts/build-webkit --qt --no-webkit2
